{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-nginx.serviceAccountName" . }}
  labels:
    app: {{ include "my-nginx.name" . }}
{{- end }}

